"use client";
import {useState} from "react";
import {useAction,useConvexAuth,useMutation,useQuery} from "convex/react";
import {api} from "@/convex/_generated/api";
import type {Doc,Id} from "@/convex/_generated/dataModel";
import {destinationHold,destinationIdentity} from "@/lib/bufferContracts";
import {linkedInPayload,socialReleaseVersion} from "@/lib/socialPayload";
import {scheduleToUtcIso} from "@/lib/schedules";
type ReviewedPost={_id:Id<"v2Posts">;title:string;content:string;linkedinFirstComment?:string;scheduledDate?:string;scheduledTime?:string;timezone?:string;platformSettings?:unknown};
export function BufferDestinationPanel({brandId,post}:{brandId:Doc<"v2Posts">["brandId"];post?:ReviewedPost}){
 const {isAuthenticated}=useConvexAuth();const row=useQuery(api.bufferDestinations.get,isAuthenticated?{brandId}:"skip") as Doc<"bufferDestinations">|null|undefined;const refresh=useAction(api.bufferLive.refreshDestination);const pin=useMutation(api.bufferDestinations.pin);const fallback=useMutation(api.bufferDestinations.bodyLinkAlternative);const confirm=useMutation(api.bufferDestinations.confirmFirstComment);
 const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [capability,setCapability]=useState<"unknown"|"supported"|"unsupported">("unknown");const [evidence,setEvidence]=useState("");const d=row?.destination;const hold=row?.error || destinationHold(d,Boolean(post?.linkedinFirstComment?.trim()));let dueAt="Review required";try{if(post?.scheduledDate&&post.scheduledTime&&post.timezone)dueAt=scheduleToUtcIso({scheduledDate:post.scheduledDate,scheduledTime:post.scheduledTime,timezone:post.timezone});}catch{/* invalid schedules remain visible */}
 async function run(fn:()=>Promise<unknown>){setBusy(true);try{const result=await fn();setMessage(result&&typeof result==="object"&&"reason"in result?String(result.reason??"Check complete"):"Saved. Review the current copy before queueing.");}catch(e){setMessage(e instanceof Error?e.message:"Connection check failed");}finally{setBusy(false);}}
 return <section aria-label="Buffer destination" className="space-y-3 rounded border p-3 text-sm"><h3 className="font-semibold">LinkedIn destination</h3>{d?<><p>{d.displayName} — LinkedIn {d.accountType}</p><p>@{d.handle} · channel {d.channelId} · organization {d.organizationId}</p>{d.profileUrl&&<a className="underline" href={d.profileUrl} target="_blank" rel="noreferrer">View destination profile</a>}<p>Checked {new Date(d.checkedAt).toLocaleString()} · first comment: {d.firstComment.value}</p><p className="text-xs">{d.firstComment.source}, {new Date(d.firstComment.checkedAt).toLocaleString()}: {d.firstComment.evidence}</p></>:<p>Destination unverified. {row?.error}</p>}{hold&&<p role="status">Held: {hold}</p>}<button className="rounded border px-3 py-2" disabled={busy||!isAuthenticated} onClick={()=>void run(()=>refresh({brandId}))}>Refresh destination</button>
 {post&&<details><summary>Review destination, payload and schedule</summary><p>{post.scheduledDate} {post.scheduledTime} {post.timezone} · UTC {dueAt}</p><pre className="whitespace-pre-wrap">{linkedInPayload(post.content,post.platformSettings)}</pre>{post.linkedinFirstComment&&<><p>First comment</p><pre className="whitespace-pre-wrap">{post.linkedinFirstComment}</pre></>}<button disabled={busy||Boolean(hold)||!d} className="rounded border px-3 py-2" onClick={()=>void run(()=>pin({postId:post._id,identity:destinationIdentity(d!),expectedVersion:socialReleaseVersion(post)}))}>Review this destination and schedule</button></details>}
 {post?.linkedinFirstComment&&<details><summary>Review body-link alternative</summary><p>This exact edit clears approval:</p><pre className="whitespace-pre-wrap">{`${post.content}\n\n${post.linkedinFirstComment}`}</pre><button disabled={busy} className="rounded border px-3 py-2" onClick={()=>void run(()=>fallback({postId:post._id,expectedVersion:socialReleaseVersion(post)}))}>Save alternative and require reapproval</button></details>}
 {d&&<details><summary>Confirm account first-comment entitlement</summary><label>Confirmed capability<select className="ml-2 rounded border p-2" value={capability} onChange={e=>setCapability(e.target.value as typeof capability)}><option value="unknown">Unknown</option><option value="supported">Supported</option><option value="unsupported">Unsupported</option></select></label><label className="block">Account plan evidence<input className="w-full rounded border p-2" value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><button disabled={busy||!evidence.trim()} onClick={()=>void run(()=>confirm({brandId,channelId:d.channelId,value:capability,evidence}))}>Confirm for displayed account</button></details>}{message&&<p role="status">{message}</p>}
 </section>;
}
export function BufferConnections(){const {isAuthenticated}=useConvexAuth();const brands=useQuery(api.publishing.listBrands,isAuthenticated?{}:"skip") as Doc<"v2Brands">[]|undefined;return <>{brands?.map(brand=><BufferDestinationPanel key={brand.brandId} brandId={brand.brandId}/>)}</>;}
