import {test,expect} from "@playwright/test";
test("composer and Connections show the exact account, held entitlement, delivery receipt and reviewed fallback",async({page})=>{
 const destination={channelId:"fixture-company-page",organizationId:"fixture-org",displayName:"Corvo Labs",handle:"corvo-labs-us",accountType:"Page",profileUrl:"https://www.linkedin.com/company/fixture",disconnected:false,locked:false,queuePaused:false,flagsVerified:true,checkedAt:Date.now(),firstComment:{value:"unsupported",source:"provider-observation",checkedAt:Date.now(),evidence:"Sanitized plan restriction fixture"}};
 let post={_id:"fixture-social",_creationTime:1,userId:"fixture-editor",brandId:"corvo",channelId:"linkedin",platformId:"linkedin",title:"Linked companion",content:"Exact approved companion copy",linkedinFirstComment:"https://corvolabs.com/blog/fixture",status:"queued",approvalState:"approved",scheduledDate:"2030-10-07",scheduledTime:"09:00",timezone:"America/Los_Angeles",contentFingerprint:"fixture",createdAt:1,updatedAt:1};const calls:string[]=[];
 const state={_id:"fixture-state",providerId:"buffer",status:"queued",providerPostId:"fixture-provider-receipt",lastCheckedAt:Date.now(),dueAt:"2030-10-07T16:00:00.000Z",destination};
 await page.route("**/api/providers/validate",r=>r.fulfill({json:{platforms:[],checkedAt:new Date().toISOString()}}));
 await page.routeWebSocket(/\/api\/.*\/sync/,socket=>{
  const qs=new Map<number,{queryId:number;udfPath:string;args:unknown[]}>();let version={querySet:0,identity:0,ts:"AAAAAAAAAAA="};let tick=0;
  function val(path:string,args:unknown[]){if(path==="publishing:listBrands")return [{brandId:"corvo",name:"Corvo Labs"}];if(path==="publishing:getPostById")return post;if(path==="publishing:listCalendarItems")return [{post,intent:{_id:"fixture-intent",scheduledDate:post.scheduledDate,scheduledTime:post.scheduledTime,timezone:post.timezone},providerState:state,attemptCount:1}];if(path==="publishing:bufferLiveSubmissionEnabled")return {enabled:false};if(path==="series:list")return [];if(path==="bufferDestinations:get")return (args[0] as {brandId:string}).brandId==="corvo"?{destination,updatedAt:Date.now()}:null;if(path==="bufferDelivery:history")return {state,receipts:[{_id:"receipt-1",createdAt:Date.now(),action:"provider.buffer_submit",summary:"Sanitized scheduling receipt",metadata:{status:"scheduled",dueAt:state.dueAt}}]};return null;}
  function send(querySet=version.querySet){const ts=Buffer.alloc(8);ts.writeBigUInt64LE(BigInt(++tick));const endVersion={...version,querySet,ts:ts.toString("base64")};socket.send(JSON.stringify({type:"Transition",startVersion:version,endVersion,modifications:[...qs.values()].map(q=>({type:"QueryUpdated",queryId:q.queryId,value:val(q.udfPath,q.args),journal:null,logLines:[]}))}));version=endVersion;}
  socket.onMessage(raw=>{const m=JSON.parse(String(raw));if(m.type==="Authenticate"){const startVersion=version;version={...version,identity:version.identity+1};socket.send(JSON.stringify({type:"Transition",startVersion,endVersion:version,modifications:[]}));}if(m.type==="ModifyQuerySet"){for(const q of m.modifications){if(q.type==="Add")qs.set(q.queryId,q);else qs.delete(q.queryId);}send(m.newVersion);}if(m.type==="Mutation"){calls.push(m.udfPath);if(m.udfPath==="bufferDestinations:bodyLinkAlternative")post={...post,content:`${post.content}\n\n${post.linkedinFirstComment}`,linkedinFirstComment:"",approvalState:"unapproved",status:"draft"};socket.send(JSON.stringify({type:"MutationResponse",requestId:m.requestId,success:true,result:null,ts:version.ts,logLines:[]}));send();}});
 });
 await page.goto("/?postId=fixture-social");const detail=page.getByLabel("Publishing item detail");await expect(detail).toBeVisible();await expect(detail.getByText("Corvo Labs — LinkedIn Page",{exact:true})).toBeVisible();await expect(detail.getByRole("link",{name:"View destination profile"})).toHaveAttribute("href",destination.profileUrl);await expect(detail.getByText(/first comment: unsupported/)).toBeVisible();await expect(detail.getByRole("heading",{name:"Delivery: Queued"})).toBeVisible();
 await detail.getByText("Sanitized receipt history").click();await expect(detail.getByText("Sanitized scheduling receipt",{exact:false})).toBeVisible();await detail.getByText("Review body-link alternative").click();await expect(detail.getByText("This exact edit clears approval:")).toBeVisible();await page.screenshot({path:"test-results/buffer-reviewed-destination.png",fullPage:true});
 await detail.getByRole("button",{name:"Save alternative and require reapproval"}).click();await expect.poll(()=>calls.includes("bufferDestinations:bodyLinkAlternative")).toBe(true);await page.reload();await expect(detail.getByLabel("First comment")).toHaveValue("");expect(calls).toEqual(["bufferDestinations:bodyLinkAlternative"]);
});
