import {test,expect} from "@playwright/test";
const posts=Array.from({length:45},(_,n)=>({_id:`post-${n}`,_creationTime:n,userId:"fixture-editor",brandId:"corvo",channelId:n%3===0?"corvo-blog":"linkedin",platformId:n%3===0?"corvo-blog":"linkedin",title:`Prepared ${n%3===0?"article":"companion"} ${n+1}`,content:`Preserved copy ${n}`,approvalState:n%3===1?"approved":"unapproved",status:n%3===1?"submitted":"draft",timezone:"America/Los_Angeles",scheduledDate:"2026-10-07",scheduledTime:"09:00",createdAt:1,updatedAt:1,contentFingerprint:"fixture"}));
test("15 articles and 30 companions persist grouping and open the canonical calendar",async({page})=>{
  let entries=Array.from({length:15},(_,n)=>({_id:`entry-${n}`,seriesId:"series-fixture",key:`key-${n}`,sequence:n+1,articlePostId:posts[n*3]._id,companionPostIds:[posts[n*3+1]._id,posts[n*3+2]._id],posts:posts.slice(n*3,n*3+3).map(post=>({post,providerState:{status:post.status==="submitted"?"submitted":"not-submitted"}}))}));
  const original=JSON.stringify(posts);const calls:string[]=[];
  await page.routeWebSocket(/\/api\/.*\/sync/,socket=>{
    const queries=new Map<number,{queryId:number;udfPath:string;args:Record<string,unknown>[]} >();let version={querySet:0,ts:"AAAAAAAAAAA=",identity:0};let clock=0;
    function value(path:string){if(path==="series:list")return [{_id:"series-fixture",title:"Prepared 15/30 series",brandId:"corvo",revision:1}];if(path==="series:get")return {_id:"series-fixture",title:"Prepared 15/30 series",brandId:"corvo",revision:1};if(path==="series:entries")return {page:entries,isDone:true,continueCursor:""};if(path==="series:picker")return {page:[],isDone:true,continueCursor:""};if(path==="publishing:listBrands")return [{brandId:"corvo",name:"Corvo Labs"}];if(path==="publishing:listCalendarItems")return entries.flatMap(e=>e.posts).map(x=>({...x,intent:{scheduledDate:x.post.scheduledDate,scheduledTime:x.post.scheduledTime,timezone:x.post.timezone},attemptCount:0}));if(path==="publishing:bufferLiveSubmissionEnabled")return {enabled:false};return null;}
    function send(querySet=version.querySet){const ts=Buffer.alloc(8);ts.writeBigUInt64LE(BigInt(++clock));const endVersion={...version,querySet,ts:ts.toString("base64")};socket.send(JSON.stringify({type:"Transition",startVersion:version,endVersion,modifications:[...queries.values()].map(q=>({type:"QueryUpdated",queryId:q.queryId,value:value(q.udfPath),journal:null,logLines:[]}))}));version=endVersion;}
    socket.onMessage(raw=>{const m=JSON.parse(String(raw));if(m.type==="Authenticate"){const startVersion=version;version={...version,identity:version.identity+1};socket.send(JSON.stringify({type:"Transition",startVersion,endVersion:version,modifications:[]}));}if(m.type==="ModifyQuerySet"){for(const q of m.modifications){if(q.type==="Add")queries.set(q.queryId,q);else queries.delete(q.queryId);}send(m.newVersion);}if(m.type==="Mutation"){calls.push(m.udfPath);const a=m.args[0];if(m.udfPath==="series:move"){const index=entries.findIndex(e=>e._id===a.entryId);const neighbor=index+(a.direction==="up"?-1:1);if(neighbor>=0&&neighbor<entries.length)[entries[index],entries[neighbor]]=[entries[neighbor],entries[index]];}if(m.udfPath==="series:detach")entries=entries.filter(e=>e._id!==a.entryId);socket.send(JSON.stringify({type:"MutationResponse",requestId:m.requestId,success:true,result:null,ts:version.ts,logLines:[]}));send();}});
  });
  await page.goto("/series?seriesId=series-fixture");await expect(page.getByLabel("Series progress")).toContainText("15 articles · 30 companions");
  await expect(page.getByRole("link",{name:"Prepared article 1",exact:true})).toHaveAttribute("href","/?postId=post-0");
  await page.getByRole("button",{name:"Move down",exact:true}).first().click();await expect.poll(()=>calls.includes("series:move")).toBe(true);
  await page.reload();await expect(page.getByRole("link",{name:/Prepared article/}).first()).toHaveText("Prepared article 4");
  await page.screenshot({path:"test-results/series-15-30.png",fullPage:true});
  await page.getByRole("link",{name:"View series in calendar"}).click();await expect(page.getByLabel("Calendar series filter")).toHaveValue("series-fixture");
  expect(JSON.stringify(posts)).toBe(original);expect(calls.every(c=>c.startsWith("series:"))).toBe(true);
});
