export interface PublishImageAltInput {
  sourceUrl: string;
  alt?: string;
  isCover?: boolean;
}

interface AltGenerationParams {
  title: string;
  excerpt?: string;
  coverImageAlt?: string;
  images?: PublishImageAltInput[];
}

interface AltGenerationResult {
  coverImageAlt?: string;
  images?: PublishImageAltInput[];
}

function normalizeText(value?: string) {
  return value?.replace(/\s+/g, " ").trim() ?? "";
}

// Detect alt text that is clearly a placeholder or autogenerated filename so
// we can regenerate it. The prior catch-all `^[a-z0-9._-]+$` was too broad —
// it flagged valid one-word alt text like "diagram" or "logo" as placeholder.
// We now match only:
//   - empty/whitespace-only strings
//   - the literal generic words we emit as fallbacks
//   - filename-like tokens with an image extension (e.g. "hero.png")
//   - autogenerated camera/screenshot/stub names followed by digits
//     (e.g. "IMG_0001", "image-1", "dsc00042", "screenshot2", "untitled-3")
function isLikelyPlaceholderAlt(value?: string) {
  const normalized = normalizeText(value);
  if (!normalized) return true;
  if (/^(image|post image|hero|cover|figure)$/i.test(normalized)) return true;
  if (/^[a-z0-9._-]+\.(jpe?g|png|gif|webp|svg|avif|heic|bmp|tiff?)$/i.test(normalized)) {
    return true;
  }
  if (
    /^(img|image|photo|pic|picture|figure|fig|dsc|dscn|screenshot|screen[\s_-]?shot|untitled)[\s_-]*\d+$/i.test(
      normalized
    )
  ) {
    return true;
  }
  return false;
}

function getZaiAltConfig() {
  const apiKey = process.env.ZAI_API_KEY?.trim();
  if (!apiKey) {
    throw new Error("Missing required environment variable: ZAI_API_KEY");
  }

  return {
    apiKey,
    baseUrl: process.env.ZAI_BASE_URL?.trim() || "https://api.z.ai/api/paas/v4",
    model: process.env.ZAI_ALT_MODEL?.trim() || "glm-4.5v",
  };
}

function fallbackAlt(title: string, index: number, isCover: boolean) {
  if (isCover) return `Cover image for ${title}`;
  return `Illustration ${index + 1} accompanying ${title}`;
}

function extractResponseText(content: unknown): string {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";

  return content
    .map((entry) => {
      if (!entry || typeof entry !== "object") return "";
      const candidate = entry as { type?: unknown; text?: unknown };
      return candidate.type === "text" && typeof candidate.text === "string"
        ? candidate.text
        : "";
    })
    .join("\n");
}

function extractJsonObject(raw: string): string | null {
  const start = raw.indexOf("{");
  const end = raw.lastIndexOf("}");
  if (start === -1 || end === -1 || end < start) return null;
  return raw.slice(start, end + 1);
}

export async function enrichPublishImageAlts(
  params: AltGenerationParams
): Promise<AltGenerationResult> {
  const images = params.images ?? [];
  if (images.length === 0) {
    return {
      coverImageAlt: normalizeText(params.coverImageAlt) || undefined,
      images,
    };
  }

  const fallbackImages = images.map((image, index) => ({
    ...image,
    alt: isLikelyPlaceholderAlt(image.alt)
      ? fallbackAlt(params.title, index, Boolean(image.isCover))
      : normalizeText(image.alt),
  }));
  const fallbackCoverImageAlt =
    isLikelyPlaceholderAlt(params.coverImageAlt)
      ? fallbackImages.find((image) => image.isCover)?.alt || fallbackAlt(params.title, 0, true)
      : normalizeText(params.coverImageAlt) || undefined;

  let config: ReturnType<typeof getZaiAltConfig>;
  try {
    config = getZaiAltConfig();
  } catch {
    return {
      coverImageAlt: fallbackCoverImageAlt,
      images: fallbackImages,
    };
  }

  const userContent = [
    {
      type: "text",
      text: [
        "Generate concise, accessible alt text for every attached blog post image.",
        "Return JSON only in this exact shape:",
        '{"coverImageAlt":"...", "images":[{"index":0,"alt":"..."}]}',
        `Post title: ${params.title}`,
        params.excerpt ? `Post excerpt: ${params.excerpt}` : "",
        "Requirements:",
        "- Be factual and objective.",
        "- One sentence per image.",
        "- Do not mention 'image of'.",
        "- Keep each alt text under 160 characters.",
        "- Include every image index exactly once.",
      ]
        .filter(Boolean)
        .join("\n"),
    },
    ...images.flatMap((image, index) => [
      { type: "text", text: `Image ${index}${image.isCover ? " (cover)" : ""}` },
      { type: "image_url", image_url: { url: image.sourceUrl } },
    ]),
  ];

  try {
    const response = await fetch(`${config.baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${config.apiKey}`,
        "Accept-Language": "en-US,en",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: config.model,
        messages: [
          {
            role: "system",
            content:
              "You write accessibility alt text for web content. Return valid JSON only.",
          },
          {
            role: "user",
            content: userContent,
          },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`Alt text API error: ${response.status}`);
    }

    const payload = await response.json();
    const rawText = extractResponseText(payload?.choices?.[0]?.message?.content);
    const jsonText = extractJsonObject(rawText);
    if (!jsonText) throw new Error("Alt text response did not contain JSON.");

    const parsed = JSON.parse(jsonText) as {
      coverImageAlt?: unknown;
      images?: Array<{ index?: unknown; alt?: unknown }>;
    };

    const generatedByIndex = new Map<number, string>();
    for (const item of parsed.images ?? []) {
      if (
        typeof item?.index === "number" &&
        typeof item?.alt === "string" &&
        normalizeText(item.alt)
      ) {
        generatedByIndex.set(item.index, normalizeText(item.alt));
      }
    }

    const nextImages = fallbackImages.map((image, index) => ({
      ...image,
      alt: generatedByIndex.get(index) || image.alt,
    }));

    const nextCoverImageAlt =
      typeof parsed.coverImageAlt === "string" && normalizeText(parsed.coverImageAlt)
        ? normalizeText(parsed.coverImageAlt)
        : fallbackCoverImageAlt;

    return {
      coverImageAlt: nextCoverImageAlt,
      images: nextImages,
    };
  } catch {
    return {
      coverImageAlt: fallbackCoverImageAlt,
      images: fallbackImages,
    };
  }
}
