import {describe,it,expect,vi} from "vitest";
import {destinationHold,destinationIdentity,observeBufferRateLimit,safeLinkedInUrl,type BufferDestination} from "../bufferContracts";
import {bufferProviderAdapter,mapBufferPostStatus,resolveBufferLinkedInChannelId} from "../providerAdapters";
const now=Date.now();const destination:BufferDestination={channelId:"page-id",organizationId:"org-id",displayName:"Fixture Company",handle:"corvo-labs-us",accountType:"page",disconnected:false,locked:false,queuePaused:false,flagsVerified:true,checkedAt:now,firstComment:{value:"unknown",source:"unknown",checkedAt:now,evidence:"No entitlement field"}};
const context={env:{BUFFER_API_KEY:"sanitized-fixture-secret",BUFFER_LIVE_SUBMISSION:"approved"},liveProviderValidationApproved:true};
function discovery(channel:Record<string,unknown>={}) {return [new Response(JSON.stringify({data:{account:{organizations:[{id:"org-id"}]}}})),new Response(JSON.stringify({data:{channels:[{id:"page-id",organizationId:"org-id",name:"corvo-labs-us",displayName:"Fixture Company",type:"page",service:"linkedin",externalLink:"https://www.linkedin.com/company/fixture",isDisconnected:false,isLocked:false,isQueuePaused:false,...channel}]}}))];}
describe("Buffer destination and request contracts",()=>{
 it("uses documented identity/type/flags and retains unknown capability without account data",async()=>{const fetchImpl=vi.fn();for(const response of discovery())fetchImpl.mockResolvedValueOnce(response);const result=await resolveBufferLinkedInChannelId("corvo",{...context,fetchImpl});expect(result).toMatchObject({ok:true,destination:{channelId:"page-id",organizationId:"org-id",accountType:"page",firstComment:{value:"unknown"}}});expect(JSON.stringify(result)).not.toContain("sanitized-fixture-secret");expect(safeLinkedInUrl("http://127.0.0.1/private")).toBeUndefined();});
 it.each(["disconnected","locked","queuePaused"] as const)("holds a %s destination",flag=>expect(destinationHold({...destination,[flag]:true},false)).not.toBeNull());
 it("body links work with unknown entitlement while required comments and stale evidence hold",()=>{expect(destinationHold(destination,false,now)).toBeNull();expect(destinationHold(destination,true,now)).toMatch(/unknown/);expect(destinationHold({...destination,checkedAt:now-16*60*1000},false,now)).toMatch(/stale/);expect(destinationIdentity(destination)).not.toBe(destinationIdentity({...destination,channelId:"other"}));});
 it.each([{id:"other-page"},{isQueuePaused:true},{isLocked:true},{isDisconnected:true}])("does not create when the reviewed channel is redirected or unusable: %o",async change=>{
  const fetchImpl=vi.fn();for(const response of discovery(change))fetchImpl.mockResolvedValueOnce(response);const result=await bufferProviderAdapter.submit({postId:"fixture",brandId:"corvo",channelId:"linkedin",title:"Fixture",content:"Exact body link https://corvolabs.com",scheduledDate:"2030-10-07",scheduledTime:"09:00",timezone:"America/Los_Angeles",idempotencyKey:"fixture",expectedDestination:destination},{...context,fetchImpl});expect(result.ok).toBe(false);expect(fetchImpl).toHaveBeenCalledTimes(2);expect(fetchImpl.mock.calls.some(([,init])=>String(init.body).includes("createPost"))).toBe(false);
 });
 it("does not create an unsupported first comment",async()=>{const fetchImpl=vi.fn();for(const response of discovery())fetchImpl.mockResolvedValueOnce(response);const result=await bufferProviderAdapter.submit({postId:"fixture",brandId:"corvo",channelId:"linkedin",title:"Fixture",content:"Exact copy",firstComment:"https://corvolabs.com",scheduledDate:"2030-10-07",timezone:"America/Los_Angeles",idempotencyKey:"fixture",expectedDestination:destination},{...context,fetchImpl});expect(result.reason).toMatch(/unknown/);expect(fetchImpl).toHaveBeenCalledTimes(2);});
 it.each([["scheduled","queued"],["sending","publishing"],["sent","published"],["error","failed"],["needs_approval","needs-review"],["draft","provider-draft"],["new-state","needs-review"]])("normalizes %s to %s",(provider,status)=>expect(mapBufferPostStatus(provider)).toBe(status));
 it("honors all rate windows and Retry-After without retrying",()=>{const budget={remaining:20,backoffUntil:undefined as number|undefined};observeBufferRateLimit(new Response("{}",{status:429,headers:{RateLimit:'"15min"; r=8; t=20, "1day"; r=0; t=86400',"Retry-After":"86400"}}),budget,now);expect(budget.remaining).toBe(0);expect(budget.backoffUntil).toBe(now+86400000);});
});
