// @vitest-environment node
import { beforeEach, describe, expect, it, vi } from "vitest";
import { enrichPublishImageAlts } from "@/lib/imageAlt";

describe("enrichPublishImageAlts", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    delete process.env.ZAI_API_KEY;
    delete process.env.ZAI_BASE_URL;
    delete process.env.ZAI_ALT_MODEL;
  });

  it("returns deterministic fallback alt text when no AI provider is configured", async () => {
    const result = await enrichPublishImageAlts({
      title: "Shipping Better Posts",
      images: [
        { sourceUrl: "https://cdn.example.com/hero.webp", alt: "hero", isCover: true },
        {
          sourceUrl: "https://cdn.example.com/pipeline.webp",
          alt: "IMG_0042",
        },
      ],
      coverImageAlt: "",
    });

    expect(result.coverImageAlt).toBe("Cover image for Shipping Better Posts");
    expect(result.images).toEqual([
      {
        sourceUrl: "https://cdn.example.com/hero.webp",
        alt: "Cover image for Shipping Better Posts",
        isCover: true,
      },
      {
        sourceUrl: "https://cdn.example.com/pipeline.webp",
        alt: "Illustration 2 accompanying Shipping Better Posts",
      },
    ]);
  });

  it("preserves valid author-supplied alt text that isn't a placeholder", async () => {
    const result = await enrichPublishImageAlts({
      title: "Shipping Better Posts",
      coverImageAlt: "Diagram",
      images: [
        {
          sourceUrl: "https://cdn.example.com/hero.webp",
          alt: "Diagram",
          isCover: true,
        },
        {
          sourceUrl: "https://cdn.example.com/logo.webp",
          alt: "Logo",
        },
        {
          sourceUrl: "https://cdn.example.com/pipeline.webp",
          alt: "pipeline-overview",
        },
      ],
    });

    expect(result.coverImageAlt).toBe("Diagram");
    expect(result.images?.[0].alt).toBe("Diagram");
    expect(result.images?.[1].alt).toBe("Logo");
    expect(result.images?.[2].alt).toBe("pipeline-overview");
  });

  it("treats filename-like and autogenerated tokens as placeholders", async () => {
    const result = await enrichPublishImageAlts({
      title: "Shipping Better Posts",
      images: [
        {
          sourceUrl: "https://cdn.example.com/hero.webp",
          alt: "hero.png",
          isCover: true,
        },
        {
          sourceUrl: "https://cdn.example.com/pipeline.webp",
          alt: "screenshot-2024",
        },
      ],
    });

    expect(result.images?.[0].alt).toBe("Cover image for Shipping Better Posts");
    expect(result.images?.[1].alt).toBe(
      "Illustration 2 accompanying Shipping Better Posts"
    );
  });

  it("uses a Z.AI GLM model to generate alt text for every image", async () => {
    process.env.ZAI_API_KEY = "test-key";
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue(
        new Response(
          JSON.stringify({
            choices: [
              {
                message: {
                  content: JSON.stringify({
                    coverImageAlt: "Dashboard showing the editorial workflow and publishing states.",
                    images: [
                      {
                        index: 0,
                        alt: "Dashboard showing the editorial workflow and publishing states.",
                      },
                      {
                        index: 1,
                        alt: "Diagram tracing draft handoff from editor to published blog assets.",
                      },
                    ],
                  }),
                },
              },
            ],
          }),
          { status: 200 }
        )
      )
    );

    const result = await enrichPublishImageAlts({
      title: "Shipping Better Posts",
      excerpt: "How the publish pipeline works.",
      coverImageAlt: "",
      images: [
        { sourceUrl: "https://cdn.example.com/hero.webp", alt: "hero", isCover: true },
        {
          sourceUrl: "https://cdn.example.com/pipeline.webp",
          alt: "pipeline-overview",
        },
      ],
    });

    expect(fetch).toHaveBeenCalledWith(
      "https://api.z.ai/api/paas/v4/chat/completions",
      expect.objectContaining({
        method: "POST",
        headers: expect.objectContaining({
          Authorization: "Bearer test-key",
          "Accept-Language": "en-US,en",
        }),
      })
    );

    const [, requestInit] = vi.mocked(fetch).mock.calls[0];
    const body = JSON.parse((requestInit as RequestInit).body as string);
    expect(body.model).toBe("glm-4.5v");
    expect(body.messages[1].content).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ type: "text", text: expect.stringContaining("Image 0 (cover)") }),
        expect.objectContaining({
          type: "image_url",
          image_url: { url: "https://cdn.example.com/hero.webp" },
        }),
        expect.objectContaining({ type: "text", text: expect.stringContaining("Image 1") }),
        expect.objectContaining({
          type: "image_url",
          image_url: { url: "https://cdn.example.com/pipeline.webp" },
        }),
      ])
    );

    expect(result.coverImageAlt).toBe(
      "Dashboard showing the editorial workflow and publishing states."
    );
    expect(result.images?.[0].alt).toBe(
      "Dashboard showing the editorial workflow and publishing states."
    );
    expect(result.images?.[1].alt).toBe(
      "Diagram tracing draft handoff from editor to published blog assets."
    );
  });

  it("overrides existing alt text when Z.AI returns fresh alt text for all images", async () => {
    process.env.ZAI_API_KEY = "test-key";
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue(
        new Response(
          JSON.stringify({
            choices: [
              {
                message: {
                  content: JSON.stringify({
                    coverImageAlt: "Founder reviewing a post draft beside a large analytics display.",
                    images: [
                      {
                        index: 0,
                        alt: "Founder reviewing a post draft beside a large analytics display.",
                      },
                    ],
                  }),
                },
              },
            ],
          }),
          { status: 200 }
        )
      )
    );

    const result = await enrichPublishImageAlts({
      title: "Shipping Better Posts",
      coverImageAlt: "Team reviewing a content calendar on a large monitor.",
      images: [
        {
          sourceUrl: "https://cdn.example.com/hero.webp",
          alt: "Team reviewing a content calendar on a large monitor.",
          isCover: true,
        },
      ],
    });

    expect(result.coverImageAlt).toBe(
      "Founder reviewing a post draft beside a large analytics display."
    );
    expect(result.images?.[0].alt).toBe(
      "Founder reviewing a post draft beside a large analytics display."
    );
  });
});
